ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_passing;
--;;
ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_ball_control;
--;;
ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_carrying;
--;;
ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_shooting;
--;;
ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_dribbling;
--;;
ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_defending;
--;;
ALTER TABLE "OrganizationPlayers" DROP COLUMN IF EXISTS "passing";
--;;
ALTER TABLE "OrganizationPlayers" DROP COLUMN IF EXISTS "ball_control";
--;;
ALTER TABLE "OrganizationPlayers" DROP COLUMN IF EXISTS "carrying";
--;;
ALTER TABLE "OrganizationPlayers" DROP COLUMN IF EXISTS "shooting";
--;;
ALTER TABLE "OrganizationPlayers" DROP COLUMN IF EXISTS "dribbling";
--;;
ALTER TABLE "OrganizationPlayers" DROP COLUMN IF EXISTS "defending";
