ALTER TABLE "Peladas" DROP COLUMN "timer_started_at";
--;;
ALTER TABLE "Peladas" DROP COLUMN "timer_accumulated_ms";
--;;
ALTER TABLE "Peladas" DROP COLUMN "timer_status";
--;;
ALTER TABLE "Matches" DROP COLUMN "timer_started_at";
--;;
ALTER TABLE "Matches" DROP COLUMN "timer_accumulated_ms";
--;;
ALTER TABLE "Matches" DROP COLUMN "timer_status";
--;;
ALTER TABLE "MatchEvents" DROP COLUMN "session_time_ms";
--;;
ALTER TABLE "MatchEvents" DROP COLUMN "match_time_ms";
