ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS is_super_admin BOOLEAN DEFAULT FALSE;
--;;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS is_blocked BOOLEAN DEFAULT FALSE;
--;;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS allow_org_creation BOOLEAN DEFAULT TRUE;
--;;
ALTER TABLE "Organizations" ADD COLUMN IF NOT EXISTS is_blocked BOOLEAN DEFAULT FALSE;
