ALTER TABLE "Peladas" ADD COLUMN "timer_started_at" TIMESTAMP;
--;;
ALTER TABLE "Peladas" ADD COLUMN "timer_accumulated_ms" INTEGER DEFAULT 0;
--;;
ALTER TABLE "Peladas" ADD COLUMN "timer_status" VARCHAR DEFAULT 'stopped' CHECK (timer_status IN ('stopped', 'running', 'paused'));
--;;
ALTER TABLE "Matches" ADD COLUMN "timer_started_at" TIMESTAMP;
--;;
ALTER TABLE "Matches" ADD COLUMN "timer_accumulated_ms" INTEGER DEFAULT 0;
--;;
ALTER TABLE "Matches" ADD COLUMN "timer_status" VARCHAR DEFAULT 'stopped' CHECK (timer_status IN ('stopped', 'running', 'paused'));
--;;
ALTER TABLE "MatchEvents" ADD COLUMN "session_time_ms" INTEGER;
--;;
ALTER TABLE "MatchEvents" ADD COLUMN "match_time_ms" INTEGER;
