ALTER TABLE "OrganizationPlayers" ADD COLUMN IF NOT EXISTS "passing" INTEGER DEFAULT 0;
--;;
ALTER TABLE "OrganizationPlayers" ADD COLUMN IF NOT EXISTS "ball_control" INTEGER DEFAULT 0;
--;;
ALTER TABLE "OrganizationPlayers" ADD COLUMN IF NOT EXISTS "carrying" INTEGER DEFAULT 0;
--;;
ALTER TABLE "OrganizationPlayers" ADD COLUMN IF NOT EXISTS "shooting" INTEGER DEFAULT 0;
--;;
ALTER TABLE "OrganizationPlayers" ADD COLUMN IF NOT EXISTS "dribbling" INTEGER DEFAULT 0;
--;;
ALTER TABLE "OrganizationPlayers" ADD COLUMN IF NOT EXISTS "defending" INTEGER DEFAULT 0;
--;;
ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_passing;
--;;
ALTER TABLE "OrganizationPlayers" ADD CONSTRAINT chk_passing CHECK (passing >= 0 AND passing <= 5);
--;;
ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_ball_control;
--;;
ALTER TABLE "OrganizationPlayers" ADD CONSTRAINT chk_ball_control CHECK (ball_control >= 0 AND ball_control <= 5);
--;;
ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_carrying;
--;;
ALTER TABLE "OrganizationPlayers" ADD CONSTRAINT chk_carrying CHECK (carrying >= 0 AND carrying <= 5);
--;;
ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_shooting;
--;;
ALTER TABLE "OrganizationPlayers" ADD CONSTRAINT chk_shooting CHECK (shooting >= 0 AND shooting <= 5);
--;;
ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_dribbling;
--;;
ALTER TABLE "OrganizationPlayers" ADD CONSTRAINT chk_dribbling CHECK (dribbling >= 0 AND dribbling <= 5);
--;;
ALTER TABLE "OrganizationPlayers" DROP CONSTRAINT IF EXISTS chk_defending;
--;;
ALTER TABLE "OrganizationPlayers" ADD CONSTRAINT chk_defending CHECK (defending >= 0 AND defending <= 5);
